FROM python:3.9

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
RUN python -m spacy download en_core_web_sm

COPY . /app

CMD ["python3.9", "recommendation_system_app.py", "--config_file", "app/config/backend-portal-recommender-prod.yaml"]
