version: "3.5"

services:
  mongo:
    image: mongo:6.0
    container_name: internal_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $INTERNAL_MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $INTERNAL_MONGO_PASSWORD
    networks:
      - EOSC_RECOMMENDATION_SYSTEM_APP
    volumes:
      - type: volume
        source: EOSC_RS_INTERNAL_MONGO_DATA
        target: /data/db
      - type: volume
        source: EOSC_RS_INTERNAL_MONGO_CONFIG
        target: /data/configdb

  redis:
    image: redis:6.2-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass $INTERNAL_REDIS_PASSWORD
    networks:
      - EOSC_RECOMMENDATION_SYSTEM_APP
    volumes:
      - type: volume
        source: EOSCF_RS_INTERNAL_REDIS_DATA
        target: /data

  app:
    build: .
    container_name: recommendation-system-app
    ports:
      - "0.0.0.0:4559:4559"
    networks:
      - EOSC_RECOMMENDATION_SYSTEM_APP
    depends_on:
      - mongo
      - redis


networks:
  EOSC_RECOMMENDATION_SYSTEM_APP:
    name: EOSC_RECOMMENDATION_SYSTEM_APP

volumes:
  EOSC_RS_INTERNAL_MONGO_DATA:
    name: EOSC_RS_INTERNAL_MONGO_DATA
  EOSC_RS_INTERNAL_MONGO_CONFIG:
    name: EOSC_RS_INTERNAL_MONGO_CONFIG
  EOSCF_RS_REDIS_DATA:
    name: EOSCF_RS_REDIS_DATA
