version: "3.5"

services:
  mongo:
    image: mongo:latest
    container_name: internal_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $INTERNAL_MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $INTERNAL_MONGO_PASSWORD
    networks:
      - EOSC_RECOMMENDATION_SYSTEM_APP
    volumes:
      - type: volume
        source: EOSCF_RS_INTERNAL_MONGO_DATA
        target: /data/db
      - type: volume
        source: EOSCF_RS_INTERNAL_MONGO_CONFIG
        target: /data/configdb

  app:
    build: .
    container_name: recommendation-system-app
    ports:
      - "0.0.0.0:4559:4559"
    networks:
      - EOSC_RECOMMENDATION_SYSTEM_APP
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - mongo


networks:
  EOSC_RECOMMENDATION_SYSTEM_APP:
    name: EOSC_RECOMMENDATION_SYSTEM_APP

volumes:
  EOSCF_RS_INTERNAL_MONGO_DATA:
    name: EOSCF_RS_INTERNAL_MONGO_DATA
  EOSCF_RS_INTERNAL_MONGO_CONFIG:
    name: EOSCF_RS_INTERNAL_MONGO_CONFIG
