VERSION_NAME: "v2"
MODE: "PROVIDERS-RECOMMENDER"

FASTAPI:
  WORKERS: 1
  DEBUG: True
  RELOAD: True
  HOST: '0.0.0.0'
  PORT: 4559

# In dev no scheduled updates will occur
SCHEDULING:
  EVERY_N_HOURS: 1

CREDENTIALS: "credentials.yml"

SPACY_MODEL: "en_core_web_sm"

SIMILAR_SERVICES:

  METADATA: ["categories", "scientific_domains"]
  TEXT_ATTRIBUTES: ["tagline", "description"]
  SENTENCE_FILTERING_METHOD: "NONE"  # NONE, KEYWORD, NER


  METADATA_WEIGHT: 0.5
  VIEWED_WEIGHT: 0.5

  METHOD: "SBERT" # tf-idf or SBERT
  SBERT:
    MODEL_NAME: 'paraphrase-MiniLM-L6-v2'
    DEVICE: "cpu"

PROJECT_COMPLETION:

  MIN_SUPPORT: 0.05
  MIN_CONFIDENCE: 0.5

AUTO_COMPLETION:
  ENUMERATED_FIELDS:
    categories:
      SIMILARITY_THRESHOLD: 0.5
      CONSIDERED_SERVICES_THRESHOLD: 5
      FREQUENCY_THRESHOLD: 0.1

    scientific_domains:
      SIMILARITY_THRESHOLD: 0.5
      CONSIDERED_SERVICES_THRESHOLD: 5
      FREQUENCY_THRESHOLD: 0.1

    target_users:
      SIMILARITY_THRESHOLD: 0.3
      CONSIDERED_SERVICES_THRESHOLD: 5
      FREQUENCY_THRESHOLD: 0.1

  TAGS:
    KEYWORD_EXTRACTION_METHOD: "textrank"
    SCORE_WEIGHT: 0.7
    MAX_WORDS: 3
    TEXT_ATTRIBUTES: ['tagline', 'description']
    PHRASES_SIM_THRESHOLD: 0.7
    PHRASES_EQUAL_THRESHOLD: 0.9
