VERSION_NAME: "v1"

FASTAPI:
  WORKERS: 1
  DEBUG: True
  RELOAD: True
  HOST: '0.0.0.0'
  PORT: 4559

# In dev no scheduled updates will occur
SCHEDULING:
  EVERY_N_HOURS: 1

CREDENTIALS: "credentials.yml"

SIMILAR_SERVICES:
  METADATA: ["categories", "scientific_domains", "target_users"]
  TEXT_ATTRIBUTES: ["name", "description"]

  METADATA_WEIGHT: 0.5
  VIEWED_WEIGHT: 0.5

  SBERT:
    MODEL: 'paraphrase-MiniLM-L6-v2'
    DEVICE: "cpu"

PROJECT_COMPLETION:

  MIN_SUPPORT: 0.05
  MIN_CONFIDENCE: 0.5
