FASTAPI:
  WORKERS: 4
  DEBUG: False
  RELOAD: False
  HOST: '0.0.0.0'
  PORT: 4559

CREDENTIALS: "credentials.yml"

SIMILAR_SERVICES:
  METADATA: {"categories", "scientific_domains", "target_users"}

  SBERT:
    MODEL: 'paraphrase-MiniLM-L6-v2'
    DEVICE: "cpu"

  BINARIZERS_STORAGE_PATH: "api/recommender/similar_services/storage/binarizers"
  EMBEDDINGS_STORAGE_PATH: "api/recommender/similar_services/storage/embeddings/"
  SIMILARITIES_STORAGE_PATH: "api/recommender/similar_services/storage/similarities/"

PROJECT_COMPLETION:
  ASSOCIATION_RULES_PATH: "api/recommender/project_completion/storage/association_rules.parquet"