VERSION_NAME: "v1"
MODE: "RS"

FASTAPI:
  WORKERS: 4
  DEBUG: False
  RELOAD: False
  HOST: '0.0.0.0'
  PORT: 4559

SCHEDULING:
  EVERY_N_HOURS: 1

CREDENTIALS: "credentials.yml"

SIMILAR_SERVICES:
  METADATA: ["categories", "scientific_domains", "target_users"]
  TEXT_ATTRIBUTES: ["name", "description"]

  METADATA_WEIGHT: 0.5
  VIEWED_WEIGHT: 0.5

  METHOD: "SBERT" # tf-idf or SBERT
  SBERT:
    MODEL_NAME: 'paraphrase-MiniLM-L6-v2'
    DEVICE: "cpu"

PROJECT_ASSISTANT:
  SIMILARITY_THRESHOLD: 0.5

PROJECT_COMPLETION:

  MIN_SUPPORT: 0.05
  MIN_CONFIDENCE: 0.5

AUTO_COMPLETION:

  categories:
    SIMILARITY_THRESHOLD: 0.3
    CONSIDERED_SERVICES_THRESHOLD: 5
    FREQUENCY_THRESHOLD: 0

  scientific_domains:
    SIMILARITY_THRESHOLD: 0.1
    CONSIDERED_SERVICES_THRESHOLD: 5
    FREQUENCY_THRESHOLD: 0

  target_users:
    SIMILARITY_THRESHOLD: 0.1
    CONSIDERED_SERVICES_THRESHOLD: 10
    FREQUENCY_THRESHOLD: 0
